name: smart_med
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.3.0
  firebase_core: ^4.6.0
  cloud_firestore: 6.2.0
  flutter_local_notifications: ^17.2.3
  http: ^1.3.0
  timezone: ^0.9.4
  firebase_storage: ^13.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_cloud_firestore: ^4.1.0+1
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/Capsule.png
